"""Initial

Revision ID: 2b05a5a6aeac
Revises: 
Create Date: 2025-05-26 21:36:01.322837

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2b05a5a6aeac'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cards',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('meaning', sa.String(), nullable=False),
    sa.Column('image_url', sa.String(), nullable=True),
    sa.Column('date_description', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cards_id'), 'cards', ['id'], unique=False)
    op.create_table('reading_templates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reading_templates_id'), 'reading_templates', ['id'], unique=False)
    op.create_table('card_questions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('template_id', sa.Integer(), nullable=False),
    sa.Column('num', sa.Integer(), nullable=False),
    sa.Column('question', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['template_id'], ['reading_templates.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_card_questions_id'), 'card_questions', ['id'], unique=False)
    op.create_table('card_readings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('template_id', sa.Integer(), nullable=True),
    sa.Column('question', sa.String(), nullable=True),
    sa.Column('interpretation', sa.String(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('note', sa.String(), nullable=True),
    sa.Column('came_true', sa.Boolean(), nullable=True),
    sa.Column('prompt', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['template_id'], ['reading_templates.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_card_readings_id'), 'card_readings', ['id'], unique=False)
    op.create_table('cards_in_card_reading',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_reading', sa.Integer(), nullable=False),
    sa.Column('id_card', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_card'], ['cards.id'], ),
    sa.ForeignKeyConstraint(['id_reading'], ['card_readings.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cards_in_card_reading_id'), 'cards_in_card_reading', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_cards_in_card_reading_id'), table_name='cards_in_card_reading')
    op.drop_table('cards_in_card_reading')
    op.drop_index(op.f('ix_card_readings_id'), table_name='card_readings')
    op.drop_table('card_readings')
    op.drop_index(op.f('ix_card_questions_id'), table_name='card_questions')
    op.drop_table('card_questions')
    op.drop_index(op.f('ix_reading_templates_id'), table_name='reading_templates')
    op.drop_table('reading_templates')
    op.drop_index(op.f('ix_cards_id'), table_name='cards')
    op.drop_table('cards')
    # ### end Alembic commands ###
